// typescript will complain but this is more representative of code that would be
// generated by odin2 so disabling typescript for all the examples
//
// @ts-nocheck

import type { ContinuousGeneratorDDE } from "../../src/interfaces/generators/ContinuousGenerator.ts";

export interface ConstantGradDelayParams {
    m: number;
    x: number;
    c: number;
    y: number;
    yDelay1: number;
}

export const constantGradDelay: ContinuousGeneratorDDE<ConstantGradDelayParams, null, null> = {
    initial(_imports, time: number, params, internal: null, stateNext: number[]) {
        stateNext[0] = params.m;
        stateNext[1] = params.x;
        stateNext[2] = params.c;
        stateNext[3] = params.y;
        stateNext[4] = params.yDelay1;
    },

    rhs(imports, params, internal, t, state, stateDeriv) {
        stateDeriv[0] = 0;
        stateDeriv[1] = 1;
        stateDeriv[2] = 1;
    },

    output(imports, params, internal, t, state, solution) {
        const output = Array(2);
        output[0] = state[0] * state[1] + state[2];
        const [mDelay, xDelay, cDelay] = solution(t - 1);
        output[1] = mDelay * xDelay + cDelay;
        return output;
    },

    update(_imports, time: number, dt: number, state: number[], params, internal: null, stateNext: number[]) {
        if (Math.abs(time - 8) < 1e-10) {
            stateNext[0] = 100;
        }
    },

    getZeroEvery() {
        return [[2, [2]]];
    },

    buildInternal(): null {
        return null;
    },

    buildParams(imports, params) {
        const dim = imports.array.getDimObj();
        const odin = {};

        params.yDelay1 = imports.io.readReal(params, "yDelay1");
        dim.yDelay1 = [];
        params.c = imports.io.readReal(params, "c");
        dim.c = [];
        params.m = imports.io.readReal(params, "m");
        dim.m = [];
        params.y = imports.io.readReal(params, "y");
        dim.y = [];
        params.x = imports.io.readReal(params, "x");
        dim.x = [];

        const shape = new Map<string, number[]>([
            ["gradient", []],
            ["X", []],
            ["intercept", []],
            ["Y", []],
            ["Y delayed by 1", []]
        ]);
        odin.packing = new imports.Packer({ shape });

        return { ...params, dim, odin };
    },

    updateParams(_imports, params, newParams) {
        params.m = newParams.m;
        params.x = newParams.x;
        params.c = newParams.c;
        params.y = newParams.y;
        params.yDelay1 = newParams.yDelay1;
    }
};
