// typescript will complain but this is more representative of code that would be
// generated by odin2 so disabling typescript for all the examples
//
// @ts-nocheck

import type { ContinuousGeneratorODE } from "../../src/interfaces/generators/ContinuousGenerator.ts";

export interface ConstantGradNoUpdateParams {
    y: number;
    yAddOne: number;
}

export const constantGradNoUpdate: ContinuousGeneratorODE<ConstantGradNoUpdateParams, null, null> = {
    initial(_imports, time: number, params, internal: null, stateNext: number[]) {
        stateNext[0] = params.y;
        stateNext[1] = params.yAddOne;
    },

    rhs(imports, params, internal, t, state, stateDeriv) {
        stateDeriv[0] = 1;
    },

    output(imports, params, internal, t, state) {
        const output = Array(1);
        output[0] = state[0] + 1;
        return output;
    },

    buildInternal(): null {
        return null;
    },

    buildParams(imports, params) {
        const dim = imports.array.getDimObj();
        const odin = {};

        params.y = imports.io.readReal(params, "y");
        dim.y = [];
        params.yAddOne = imports.io.readReal(params, "yAddOne");
        dim.yAddOne = [];

        const shape = new Map<string, number[]>([
            ["Y", []],
            ["Y + 1", []]
        ]);
        odin.packing = new imports.Packer({ shape });

        return { ...params, dim, odin };
    },

    updateParams(_imports, params, newParams) {
        params.y = newParams.y;
        params.yAddOne = newParams.yAddOne;
    }
};
