// typescript will complain but this is more representative of code that would be
// generated by odin2 so disabling typescript for all the examples
//
// @ts-nocheck

import type { Random } from "@reside-ic/random";
import type { DiscreteGenerator } from "../../src/interfaces/generators/DiscreteGenerator.ts";

export interface WalkParams {
    n: number;
    sd: number;
}

const checkStateRange = (state: number[], params: WalkParams) => {
    if (state.length < params.n) {
        throw RangeError(`State must have length of at least ${params.n}`);
    }
};

export const discreteWalk: DiscreteGenerator<WalkParams, null, null> = {
    initial(_imports, time: number, params: WalkParams, internal: null, stateNext: number[]) {
        checkStateRange(stateNext, params);
        for (let i = 0; i < params.n; i++) {
            stateNext[i] = time;
        }
    },

    update(
        _imports,
        time: number,
        dt: number,
        state: number[],
        params: WalkParams,
        internal: null,
        stateNext: number[],
        random: Random
    ) {
        checkStateRange(state, params);
        checkStateRange(stateNext, params);
        for (let i = 0; i < params.n; i++) {
            stateNext[i] = random.normal(state[i], params.sd);
        }
    },

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    buildInternal(_imports, params: WalkParams): null {
        return null;
    },

    buildParams(imports, params: WalkParams) {
        const dim = imports.array.getDimObj();
        const odin = {};

        params.n = imports.io.readReal(params, "n");
        dim.n = [];
        params.sd = imports.io.readReal(params, "sd");
        dim.sd = [];

        const shape = new Map<string, number[]>([["values", [params.n]]]);
        odin.packing = new imports.Packer({ shape });

        return { ...params, dim, odin };
    },

    updateParams(_imports, params: WalkParams, newParams: WalkParams) {
        params.n = newParams.n;
        params.sd = newParams.sd;
    }
};
