// typescript will complain but this is more representative of code that would be
// generated by odin2 so disabling typescript for all the examples
//
// @ts-nocheck

import type { Random } from "@reside-ic/random";
import type { DiscreteGenerator } from "../../src/interfaces/generators/DiscreteGenerator.ts";

export interface SIRParams {
    N: number;
    I0: number;
    beta: number;
    gamma: number;
}

export interface SIRData {
    prevalence: number;
}

export const discreteSIR: DiscreteGenerator<SIRParams, null, SIRData> = {
    // it would be more js-ish if we returned an array, but that would
    // be harder once we work out how to get read-write slices from
    // ndarray.
    initial(_imports, time: number, params: SIRParams, internal: null, stateNext: number[]) {
        stateNext[0] = params.N - params.I0;
        stateNext[1] = params.I0;
        stateNext[2] = 0;
        stateNext[3] = 0;
        stateNext[4] = 0;
    },

    update(
        _imports,
        time: number,
        dt: number,
        state: number[],
        params: SIRParams,
        internal: null,
        stateNext: number[],
        random: Random
    ) {
        const S = state[0];
        const I = state[1];
        const R = state[2];
        const cases_cumul = state[3];
        const cases_inc = state[4];
        const p_SI = 1 - Math.exp(((-params.beta * I) / params.N) * dt);
        const p_IR = 1 - Math.exp(-params.gamma * dt);
        const n_SI = random.binomial(S, p_SI);
        const n_IR = random.binomial(I, p_IR);
        stateNext[0] = S - n_SI;
        stateNext[1] = I + n_SI - n_IR;
        stateNext[2] = R + n_IR;
        stateNext[3] = cases_cumul + n_SI;
        stateNext[4] = cases_inc + n_SI;
    },

    buildInternal(): null {
        return null;
    },

    buildParams(imports, params: SIRParams) {
        const dim = imports.array.getDimObj();
        const odin = {};

        params.N = imports.io.readInt(params, "N");
        dim.N = [];
        params.beta = imports.io.readReal(params, "beta");
        dim.beta = [];
        params.I0 = imports.io.readReal(params, "I0");
        dim.I0 = [];
        params.gamma = imports.io.readReal(params, "gamma");
        dim.gamma = [];

        const shape = new Map<string, number[]>([
            ["S", []],
            ["I", []],
            ["R", []],
            ["casesCumul", []],
            ["casesInc", []]
        ]);
        odin.packing = new imports.Packer({ shape });

        return { ...params, dim, odin };
    },

    compareData(
        imports,
        time: number,
        state: number[],
        data: SIRData,
        params: SIRParams, // eslint-disable-line @typescript-eslint/no-unused-vars
        internal: null, // eslint-disable-line @typescript-eslint/no-unused-vars
        random: Random // eslint-disable-line @typescript-eslint/no-unused-vars
    ): number {
        const observedPrevalence = data.prevalence;
        const modelledPrevalence = state[1];
        return imports.math.poissonLogDensity(observedPrevalence, modelledPrevalence);
    },

    updateParams(_imports, params: SIRParams, newParams: SIRParams) {
        // does not update N
        params.I0 = newParams.I0;
        params.beta = newParams.beta;
        params.gamma = newParams.gamma;
    }
};
