// typescript will complain but this is more representative of code that would be
// generated by odin2 so disabling typescript for all the examples
//
// @ts-nocheck

import type { DiscreteGenerator } from "../../src/interfaces/generators/DiscreteGenerator";

export interface ABState {
    a: number;
    b: number;
}

export const zeroTwice: DiscreteGenerator<ABState, null, null> = {
    initial(_imports, _time, _params, _internal, stateNext) {
        stateNext[0] = 0;
        stateNext[1] = 0;
    },

    update(_imports, _time, _dt, state, _params, _internal, stateNext) {
        stateNext[0] = state[0] + 1;
        stateNext[1] = state[1] + 1;
    },

    buildParams(imports, params) {
        const dim = imports.array.getDimObj();
        const odin = {};
        dim.x = [];
        dim.y = [];

        params.a = imports.io.readReal(params, "a");
        params.b = imports.io.readReal(params, "b");

        const shape = new Map<string, number[]>([
            ["x", []],
            ["y", []]
        ]);
        odin.packing = new imports.Packer({ shape });

        return { ...params, dim, odin };
    },

    getZeroEvery(_imports, params) {
        return [
            [params.a, [0]],
            [params.b, [1]]
        ];
    },

    buildInternal() {
        return null;
    },

    updateParams() {}
};
