import ndarray from "ndarray";
import * as dopri from "@reside-ic/dopri";
import { Random, RngStateBuiltin } from "@reside-ic/random";
import { ParticleState, SystemState, SystemSubState } from "./SystemState.ts";
import { Packer } from "./Packer.ts";
import { NamedResult, SystemInterface } from "./interfaces/System.ts";
import {
    checkIndicesForMax,
    checkIntegerInRange,
    checkNamesInPacker,
    checkTimes,
    floatIsDivisibleBy,
    isPositiveFinite,
    particleStateToArray
} from "./utils.ts";
import { ZeroEvery } from "./zero.ts";
import { SystemSimulateResult } from "./SystemSimulateResult.ts";
import { GeneratorConfig } from "./interfaces/generators/Generator.ts";
import { DiscreteGenerator } from "./interfaces/generators/DiscreteGenerator.ts";
import { ContinuousGeneratorDDE, ContinuousGeneratorODE } from "./interfaces/generators/ContinuousGenerator.ts";
import { imports } from "./interfaces/generators/Imports.ts";
import { WithOdinDim } from "./interfaces/generators/BaseGenerator.ts";

/**
 * Implementation of {@link SystemInterface} for continuous or discrete systems. Manages particle states generated by
 * stateless generators.
 *
 * @copyDoc BaseGenerator
 */
export class System<TParams, TInternal, TData> implements SystemInterface<TData> {
    protected readonly _generatorCfg: GeneratorConfig<TParams, TInternal, TData>;
    protected readonly _nParticles: number;
    protected readonly _statePacker: Packer;
    protected readonly _state: SystemState;
    protected readonly _dt: number;
    protected _params: WithOdinDim<TParams>;
    protected readonly _internal: TInternal;
    protected readonly _zeroEvery: ZeroEvery;
    protected readonly _random: Random;
    protected _time: number;
    protected _solver: dopri.Dopri | dopri.DDE | null = null;
    protected _rhsVariablesLength: number;
    protected _history: dopri.History[];

    private constructor(
        generatorCfg: GeneratorConfig<TParams, TInternal, TData>,
        params: TParams,
        time: number,
        dt: number,
        nParticles: number,
        nRhsVariables?: number,
        random?: Random
    ) {
        checkIntegerInRange("Number of particles", nParticles, 1);

        this._generatorCfg = generatorCfg;
        const { generator, isContinuous } = generatorCfg;

        if (!isContinuous) {
            if (!isPositiveFinite(dt)) {
                throw Error(`dt provided, ${dt}, must be positive and finite`);
            }
            this._dt = dt;
        } else {
            // value of 0 for _dt means we let solver pick dt and use runParticleWithSolver
            this._dt = isPositiveFinite(dt) ? dt : 0;
        }

        this._time = time;
        this._nParticles = nParticles; // number of particles per parameter set
        // we deep copy params are we will mutate these in build params
        this._params = generator.buildParams(imports, JSON.parse(JSON.stringify(params)));
        this._statePacker = this._params.odin.packing;
        const nState = this._statePacker.length; // number of state elements in the packer, as defined by the generator

        this._state = new SystemState(this._nParticles, nState);
        this._internal = generator.buildInternal(imports, this._params);
        this._zeroEvery = generator.getZeroEvery ? generator.getZeroEvery!(imports, this._params) : [];
        this._history = Array(nParticles).fill([]);

        const nVariables = this._statePacker.nVariables;
        const cleanNRhsVariables = nRhsVariables ?? nVariables;
        this._rhsVariablesLength = this._statePacker.flatLengthBetweenVariables(0, cleanNRhsVariables - 1);
        this._random = random ? random : new Random(new RngStateBuiltin());
    }

    /**
     * @param generator Discrete generator (model) implementation for the System
     * @param params parameters of type TParams for a particle
     * @param time Initial time for the system
     * @param dt Time step to be used when updating the system, will error if dt <= 0 or dt is Infinity
     * @param nParticles Number of particles
     * @param nRhsVariables Number of variables to feed into the rhs function of the generator. This
     * may be less than the number of variables of the system if some variables are calculated from
     * the output function of the generator
     * @param random Random number generator which may be used by the generator
     */
    static createDiscrete<TParams, TInternal, TData = null>(
        generator: DiscreteGenerator<TParams, TInternal, TData>,
        params: TParams,
        time: number,
        dt: number,
        nParticles: number,
        nRhsVariables?: number,
        random?: Random
    ) {
        const generatorCfg: GeneratorConfig<TParams, TInternal, TData> = {
            generator,
            isContinuous: false,
            hasDelays: false
        };
        return new System<TParams, TInternal, TData>(generatorCfg, params, time, dt, nParticles, nRhsVariables, random);
    }

    /**
     * @param generator Continuous ODE generator (model) implementation for the System
     * @param dt Time step to be used when updating the system. If the generator does not
     * have an update method or a zeroEvery method then this parameter will be ignored in
     * favour of a more optimised dt that the solver picks. Additionally, if dt <= 0 or dt
     * is Infinity the solver will ignore any update or zeroEvery method on the generator
     * and let the solver run the continuous system.
     * @copyDoc System.createDiscrete
     */
    static createODE<TParams, TInternal, TData = null>(
        generator: ContinuousGeneratorODE<TParams, TInternal, TData>,
        params: TParams,
        time: number,
        dt: number,
        nParticles: number,
        nRhsVariables?: number,
        random?: Random
    ) {
        const generatorCfg: GeneratorConfig<TParams, TInternal, TData> = {
            generator,
            isContinuous: true,
            hasDelays: false
        };
        return new System<TParams, TInternal, TData>(generatorCfg, params, time, dt, nParticles, nRhsVariables, random);
    }

    /**
     * @param generator Continuous DDE generator (model) implementation for the System
     * @copyDoc System.createODE
     */
    static createDDE<TParams, TInternal, TData = null>(
        generator: ContinuousGeneratorDDE<TParams, TInternal, TData>,
        params: TParams,
        time: number,
        dt: number,
        nParticles: number,
        nRhsVariables?: number,
        random?: Random
    ) {
        const generatorCfg: GeneratorConfig<TParams, TInternal, TData> = {
            generator,
            isContinuous: true,
            hasDelays: true
        };
        return new System<TParams, TInternal, TData>(generatorCfg, params, time, dt, nParticles, nRhsVariables, random);
    }

    /**
     * Returns the current time of the system
     */
    public get time() {
        return this._time;
    }

    /**
     * Sets the current time of the system
     * @param value
     */
    public set time(value: number) {
        this._time = value;
    }

    /**
     * Returns the current state of all particles in the system
     */
    public get state(): Readonly<SystemState> {
        return this._state as Readonly<SystemState>;
    }

    // helper method to iterate over all particles and execute the provided function
    protected iterateParticles(f: (iParticle: number) => void) {
        for (let iParticle = 0; iParticle < this._nParticles; iParticle++) {
            f(iParticle);
        }
    }

    /**
     * Initialises each particle by calling the initial method on the generator and initialises the
     * Dopri solvers if this is a continuous system.
     */
    public setStateInitial(): void {
        const { generator, isContinuous, hasDelays } = this._generatorCfg;
        if (isContinuous) {
            if (hasDelays) {
                const generatorRhs = generator.rhs.bind(null, imports, this._params, this._internal);
                const generatorOutput = generator.output?.bind(null, imports, this._params, this._internal);
                this._solver = new dopri.DDE(
                    generatorRhs,
                    this._rhsVariablesLength,
                    // these are the control params which will be added in a future ticket: mrc-6742
                    // https://mrc-ide.github.io/dopri-js/interfaces/DopriControlParam.html
                    {},
                    generatorOutput
                );
            } else {
                const generatorRhs = generator.rhs.bind(null, imports, this._params, this._internal);
                const generatorOutput = generator.output?.bind(null, imports, this._params, this._internal);
                this._solver = new dopri.Dopri(generatorRhs, this._rhsVariablesLength, {}, generatorOutput);
            }
        }

        this.iterateParticles((iParticle) => {
            const state = this._state.getParticle(iParticle);
            const arrayState = particleStateToArray(state);
            generator.initial(imports, this._time, this._params, this._internal, arrayState, this._random);
            this._state.setParticle(iParticle, arrayState);
        });
    }

    /**
     * @copyDoc SystemInterface.setState
     */
    public setState(newState: SystemSubState, particleIndices: number[] = [], stateElementIndices: number[] = []) {
        this._state.setState(newState, particleIndices, stateElementIndices);
    }

    /**
     * Runs the system from its current time to the given time, causing its state to be updated. Calls the
     * update method on the generator for each particle.
     *
     * @copyDoc SystemInterface.runToTime
     */
    public runToTime(time: number): void {
        if (time < this._time) {
            throw RangeError(`Cannot run to requested time ${time}, which is less than current time ${this._time}.`);
        }
        if (time === this._time) {
            // Already at the requested time - nothing to do
            return;
        }
        const nSteps = (time - this._time) / this._dt;
        this.iterateParticles((iParticle) => {
            const state = this.runParticle(this._state.getParticle(iParticle), nSteps, time, iParticle);
            this._state.setParticle(iParticle, state);
        });
        this._time = time;
    }

    /**
     * @copyDoc SystemInterface.simulate
     */
    public simulate(times: number[], stateElementIndices: number[] = []): SystemSimulateResult {
        checkTimes(times, this._time);
        if (stateElementIndices.length) {
            checkIndicesForMax("State Element", stateElementIndices, this._state.nStateElements - 1);
        }

        const stateIndicesToReturn = stateElementIndices.length
            ? stateElementIndices
            : [...Array(this._state.nStateElements).keys()];

        const result = new SystemSimulateResult(this._nParticles, stateIndicesToReturn.length, times.length);
        times.forEach((t, iTime) => {
            this.runToTime(t);

            this.iterateParticles((iParticle) => {
                const particle = this._state.getParticle(iParticle);
                const stateValues = stateIndicesToReturn.map((index) => particle.get(index));
                result.setValuesForTime(iParticle, iTime, stateValues);
            });
        });
        return result;
    }

    /**
     * @copyDoc SystemInterface.simulateByStateVarName
     */
    public simulateByStateVarName(times: number[], stateElementNames: string[] = []): NamedResult {
        checkTimes(times, this._time);
        if (stateElementNames.length) {
            checkNamesInPacker(stateElementNames, this._statePacker);
        }

        const stateNamesToReturn = stateElementNames.length
            ? stateElementNames
            : [...Object.keys(this._statePacker.idx)];

        const result: NamedResult = { times, values: [] };
        this.iterateParticles(() => {
          const stateObj = Object.fromEntries(stateNamesToReturn.map(name => [name, []]));
          result.values.push(stateObj);
        });

        times.forEach(t => {
            this.runToTime(t);

            this.iterateParticles((iParticle) => {
                const particleState = this._state.getParticle(iParticle);
                const particleFlatState = Array.from({ length: particleState.size })
                    .map((_, i) => particleState.get(i));
                const vars = this._statePacker.unpackArray(particleFlatState);
                
                stateNamesToReturn.forEach(name => {
                    let data;
                    const val = vars.get(name)!;
                    if (typeof val === "object") {
                        // is ndarray
                        data = val.data as number[];
                    } else {
                        data = val;
                    }
                    result.values[iParticle][name].push(data);
                });
            });
        });
        return result;
    }

    private runParticleWithDt(particleState: ParticleState, nSteps: number, iParticle: number): number[] {
        let state = particleStateToArray(particleState);
        let stateNext = [...state];
        let time = this._time;
        for (let i = 0; i < nSteps; i++) {
            this._zeroEvery.forEach(([frequency, indicesToReset]) => {
                if (floatIsDivisibleBy(time, frequency)) {
                    indicesToReset.forEach((idx) => (state[idx] = 0));
                }
            });
            const nextTime = time + this._dt;
            if (this._solver) {
                const history = this._history[iParticle];
                if (this._generatorCfg.hasDelays) {
                    this._solver.initialise(time, state.slice(0, this._rhsVariablesLength), history);
                } else {
                    this._solver.initialise(time, state.slice(0, this._rhsVariablesLength));
                }
                const solution = this._solver.run(nextTime);
                state = solution([nextTime])[0];
                stateNext = [...state];
                this._history[iParticle] = history.concat(this._solver.getHistory());
            }
            const { update } = this._generatorCfg.generator;
            if (update) {
                update(imports, time, this._dt, state, this._params, this._internal, stateNext, this._random);
            }
            time = nextTime;
            const tmp = state;
            state = stateNext;
            stateNext = tmp;
        }
        return state;
    }

    private runParticleWithSolver(particleState: ParticleState, endTime: number): number[] {
        if (!this._solver) return [];
        const state = particleStateToArray(particleState);
        this._solver.initialise(this._time, state.slice(0, this._rhsVariablesLength));
        const solution = this._solver.run(endTime);
        return solution([endTime])[0];
    }

    private runParticle(particleState: ParticleState, nSteps: number, endTime: number, iParticle: number): number[] {
        const { isContinuous, generator } = this._generatorCfg;
        const isContinuousSolver = isContinuous && this._solver;
        const noUpdateOrZeroEvery = isContinuousSolver && !generator.update && !generator.getZeroEvery;
        const invalidDt = isContinuousSolver && this._dt === 0;
        if (noUpdateOrZeroEvery || invalidDt) {
            return this.runParticleWithSolver(particleState, endTime);
        } else {
            return this.runParticleWithDt(particleState, nSteps, iParticle);
        }
    }

    /**
     * Updates parameter values in the system.
     * @param newParams Updated parameter values.
     */
    public updateParams(newParams: TParams) {
        this._generatorCfg.generator.updateParams(imports, this._params, newParams);
    }

    public compareData(data: TData) {
        const { generator } = this._generatorCfg;
        if (generator.compareData) {
            const { compareData } = generator;

            const result = ndarray(new Array(this._nParticles), [this._nParticles]);
            this.iterateParticles((iParticle) => {
                const state = this._state.getParticle(iParticle);
                const comparisonValue = compareData(
                    imports,
                    this._time,
                    particleStateToArray(state),
                    data,
                    this._params,
                    this._internal,
                    this._random
                );
                result.set(iParticle, comparisonValue);
            });
            return result;
        } else {
            throw new TypeError("Generator does not specify a compareData function");
        }
    }
}
